### ISSUE TITLE
SyntaxError: Cannot use import statement outside a module

### ISSUE THREAD

**Issue by kpachbiu88** [buynao/webm-duration-fix#1]
![image](https://user-images.githubusercontent.com/2962737/148241811-87578011-0023-4cfb-bfb1-be9984c545ab.png)

If I add "type": "module" to package.json, then I don't have an error

node -v
v16.13.0
npm -v
8.3.0

**Comment by buynao** [comment]
> ![image](https://user-images.githubusercontent.com/2962737/148241811-87578011-0023-4cfb-bfb1-be9984c545ab.png)
> 
> If I add "type": "module" to package.json, then I don't have an error
> 
> node -v v16.13.0 npm -v 8.3.0

thank you，Now fixed
