### ISSUE TITLE
Not resolving the duration issue

### ISSUE THREAD

**Issue by salmanSOFTECH** [buynao/webm-duration-fix#2]
I tried resolving the duration with this but it isn't working.

`const fixBlob = await fixWebmDuration(
            new Blob([...blobSlice], { type: mimeType })
          )
          console.log(recorder, event, fixBlob, blobSlice)

          blobSlice = []
          let file = new File([fixBlob], name, {
              lastModified: new Date().getTime(),
              type: type,
            })`

**Comment by buynao** [comment]
Is there a more detailed description of the code?

**Comment by buynao** [comment]
I wrote a demo, you can see if it can solve your problem：
https://github.com/buynao/mediaRecorder-demo

**Comment by buynao** [comment]
> I tried resolving the duration with this but it isn't working.
> 
> `const fixBlob = await fixWebmDuration( new Blob([...blobSlice], { type: mimeType }) ) console.log(recorder, event, fixBlob, blobSlice)
> 
> ```
>       blobSlice = []
>       let file = new File([fixBlob], name, {
>           lastModified: new Date().getTime(),
>           type: type,
>         })`
> ```

I wrote a demo, you can see if it can solve your problem：
https://github.com/buynao/mediaRecorder-demo
