### ISSUE TITLE
"typeof import("~/testproject/node_modules/webm-duration-fix/lib/index")" 没有调用签名

### ISSUE THREAD

**Issue by ZHENGYUN01** [buynao/webm-duration-fix#3]
"typeof import("~/testproject/node_modules/webm-duration-fix/lib/index")" 没有调用签名

Ask for help:

how can i fix it?

**Comment by buynao** [comment]
It seems to have something to do with your environment configuration。
you can refer to this [demo](https://github.com/buynao/mediaRecorder-demo)。

related questions ：https://stackoverflow.com/questions/58041723/typescript-with-express-type-typeof-importexpress-has-no-call-signatures
